// export const VUE_APP_API_URL = 'http://natapp.xinxintuan.co/api';
//export const VUE_APP_API_URL = 'https://wxapi.yixiang.co/api'
// export const VUE_APP_API_URL = '/h5api'
export const VUE_APP_API_URL = 'http://127.0.0.1:8008/api'
// export const VUE_APP_API_URL = 'http://192.168.31.223:8008/api'
//  export const VUE_APP_API_URL = 'http://natapp.xinxintuan.co/api';
// export const VUE_APP_API_URL = 'https://thapi.xinxintuan.co/api'
//  export const VUE_APP_API_URL = 'https://h5api.xinxintuan.co/api';
// export const VUE_APP_API_URL = 'https://h5api.xinxintuan.co/api';
export const VUE_APP_RESOURCES_URL = 'https://h5.yixiang.co/static'
